import {IUser} from "./list/list";

export const placeholder: IUser[] = [{
        username: 'itallo',
        fullname: 'v simões',
        email: 'email@gmail.com',
        phoneNumber: 21999999999,
        // birthday: Date,
        CEP: 21330110,
        district: 'Madureira',
        UF: 'RJ',
        street: 'Rua número 0',
        city: 'Rio de janeiro',
        id: 'gsegs'
    },
    {
        username: 'itallo',
        fullname: 'v simões',
        email: 'email@gmail.com',
        phoneNumber: 21999999999,
        // birthday: Date,
        CEP: 21330110,
        district: 'Madureira',
        UF: 'RJ',
        street: 'Rua número 0',
        city: 'Rio de janeiro',
        id: 'adwdawdafgaw'
    },
    {
        username: 'itallo',
        fullname: 'v simões',
        email: 'email@gmail.com',
        phoneNumber: 21999999999,
        // birthday: Date,
        CEP: 21330110,
        district: 'Madureira',
        UF: 'RJ',
        street: 'Rua número 0',
        city: 'Rio de janeiro',
        id: 'kjwshdalsdaddwaadlkwd'
    }
    ,{
        username: 'itallo',
        fullname: 'v simões',
        email: 'email@gmail.com',
        phoneNumber: 21999999999,
        // birthday: Date,
        CEP: 21330110,
        district: 'Madureira',
        UF: 'RJ',
        street: 'Rua número 0',
        city: 'Rio de janeiro',
        id: 'dq'
    }
    ,{
        username: 'itallo',
        fullname: 'v simões',
        email: 'email@gmail.com',
        phoneNumber: 21999999999,
        // birthday: Date,
        CEP: 21330110,
        district: 'Madureira',
        UF: 'RJ',
        street: 'Rua número 0',
        city: 'Rio de janeiro',
        id: 'kjwshdalweqwedlkwd'
    }
    ,{
        username: 'itallo',
        fullname: 'v simões',
        email: 'email@gmail.com',
        phoneNumber: 21999999999,
        // birthday: Date,
        CEP: 21330110,
        district: 'Madureira',
        UF: 'RJ',
        street: 'Rua número 0',
        city: 'Rio de janeiro',
        id: 'kjwshdaasdalwdlkwd'
    },
    {
        username: 'itallo',
        fullname: 'v simões',
        email: 'email@gmail.com',
        phoneNumber: 21999999999,
        // birthday: Date,
        CEP: 21330110,
        district: 'Madureira',
        UF: 'RJ',
        street: 'Rua número 0',
        city: 'Rio de janeiro',
        id: 'kjwshdazxwdlkwd'
    },
    {
        username: 'itallo',
        fullname: 'v simões',
        email: 'email@gmail.com',
        phoneNumber: 21999999999,
        // birthday: Date,
        CEP: 21330110,
        district: 'Madureira',
        UF: 'RJ',
        street: 'Rua número 0',
        city: 'Rio de janeiro',
        id: 'wqeqwe'
    },
    {
        username: 'itallo',
        fullname: 'v simões',
        email: 'email@gmail.com',
        phoneNumber: 21999999999,
        // birthday: Date,
        CEP: 21330110,
        district: 'Madureira',
        UF: 'RJ',
        street: 'Rua número 0',
        city: 'Rio de janeiro',
        id: 'fawf'
    },
    {
        username: 'itallo',
        fullname: 'v simões',
        email: 'email@gmail.com',
        phoneNumber: 21999999999,
        // birthday: Date,
        CEP: 21330110,
        district: 'Madureira',
        UF: 'RJ',
        street: 'Rua número 0',
        city: 'Rio de janeiro',
        id: 'kjwshddawdaalwdlkwd'
    },
    {
        username: 'itallo',
        fullname: 'v simões',
        email: 'email@gmail.com',
        phoneNumber: 21999999999,
        // birthday: Date,
        CEP: 21330110,
        district: 'Madureira',
        UF: 'RJ',
        street: 'Rua número 0',
        city: 'Rio de janeiro',
        id: 'kjwshdadwalwdlkwd'
    },
    {
        username: 'itallo',
        fullname: 'v simões',
        email: 'email@gmail.com',
        phoneNumber: 21999999999,
        // birthday: Date,
        CEP: 21330110,
        district: 'Madureira',
        UF: 'RJ',
        street: 'Rua número 0',
        city: 'Rio de janeiro',
        id: 'awd'
    },

]